version: "3.8"

networks:
  pizzahut:
    external: true

services:
  pizzahut.messagebus:
    image: rabbitmq:3-management-alpine
    container_name: 'pizzahut.messagebus'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - pizzahut_messagebus_data:/var/lib/rabbitmq/
    networks:
        - pizzahut

  pizzahut.zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

volumes:
  pizzahut_messagebus_data:
    name: pizzahut_messagebus_data

